apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

resources:
- jupyterhub-imagestream.yaml
- jupyterhub-dh-buildconfig.yaml
#resources:
patchesJson6902:
- target:
    group: apps.openshift.io
    kind: DeploymentConfig
    version: v1
    name: jupyterhub
  path: jupyterhub-dc.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: jupyterhub-ldap
    envs:
      - params.env

vars:
  - name: LDAP_BIND_DN_DC
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: jupyterhub-ldap
    fieldref:
      fieldpath: data.LDAP_BIND_DN_DC
  - name: LDAP_HOST
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: jupyterhub-ldap 
    fieldref:
      fieldpath: data.LDAP_HOST
  - name: LDAP_USE_SSL
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: jupyterhub-ldap 
    fieldref:
      fieldpath: data.LDAP_USE_SSL
  - name: LDAP_ALLOWED_GROUPS
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: jupyterhub-ldap 
    fieldref:
      fieldpath: data.LDAP_ALLOWED_GROUPS
  - name: JUPYTERHUB_AUTH_STATE
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: jupyterhub-ldap 
    fieldref:
      fieldpath: data.JUPYTERHUB_AUTH_STATE
  - name: LDAP_AUTH_STATE_ATTR
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: jupyterhub-ldap 
    fieldref:
      fieldpath: data.LDAP_AUTH_STATE_ATTR
  - name: ldap_credentials_secret
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: jupyterhub-ldap 
    fieldref:
      fieldpath: data.ldap_credentials_secret
  - name: jupyterhub_internal_secret
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: jupyterhub-ldap 
    fieldref:
      fieldpath: data.jupyterhub_internal_secret


configurations:
  - params.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub
