apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

resources:
- jupyterhub-imagestream.yaml
- jupyterhub-dh-buildconfig.yaml
#resources:
patchesJson6902:
- target:
    group: apps.openshift.io
    kind: DeploymentConfig
    version: v1
    name: jupyterhub
  path: jupyterhub-dc.yaml


secretGenerator:
- name: jupyterhub-ldap-secret
  env: params.env
generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub
