apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

#resources:
patchesJson6902:
- target:
    group: apps.openshift.io
    kind: BuildConfig
    name: jupyterhub-img
    version: v1
  path: jupyterhub-dh-buildconfig.yaml
- target:
    group: apps.openshift.io
    kind: ImageStream
    version: v1
    name: jupyterhub
  path: jupyterhub-imagestream.yaml
- target:
    group: apps.openshift.io
    kind: BuildConfig
    version: v1
    name: jupyterhub
  path: jupyterhub-buildconfig.yaml
- target:
    group: apps.openshift.io
    kind: ConfigMap
    version: v1
    name: jupyterhub-cfg
  path: jupyterhub-configmap.yaml
- target:
    group: apps.openshift.io
    kind: DeploymentConfig
    version: v1
    name: jupyterhub
  path: jupyterhub-dc.yaml


commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub
