apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

resources:
- jupyterhub-imagestream.yaml
- jupyterhub-buildconfig.yaml
- jupyterhub-dh-buildconfig.yaml

#resources:
patchesJson6902:
- target:
    kind: ConfigMap
    version: v1
    name: jupyterhub-cfg
  path: jupyterhub-configmap.yaml
- target:
    group: apps.openshift.io
    kind: DeploymentConfig
    version: v1
    name: jupyterhub
  path: jupyterhub-dc.yaml


commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub
