apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- jupyterhub-imagestream.yaml
- jupyterhub-buildconfig.yaml
- jupyterhub-dh-buildconfig.yaml
- jupyterhub-configmap.yaml
- jupyterhub-dc.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub
