---
varReference:
  - path: spec/template/spec/containers[]/env[]/valueFrom/secretKeyRef/name
    kind: DeploymentConfig
  - path: spec/template/spec/containers[]/env[]/valueFrom/configMapKeyRef/name
    kind: DeploymentConfig
  - path: spec/template/spec/volumes[]/configMap/name
    kind: DeploymentConfig